[project]
name = "export"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.48",
    "fastapi[standard]>=0.118.2",
    "requests>=2.32.5",
    "ruff>=0.14.0",
]
